services:
  modu-api:
    image: node:20
    container_name: modu-api
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >
      sh -c "npm install &&
             npm start"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://modu-mongodb:27017/modu
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRES_IN=1d
    depends_on:
      - modu-mongodb
    networks:
      - modu-network

  modu-mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    networks:
      - modu-network

  # modu-admin:
  #   build:
  #     context: ./admin
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./admin:/app
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3001
  #     - API_URL=http://modu-api:3000
  #   depends_on:
  #     - modu-api
  #   networks:
  #     - modu-network

  modu-frontend:
    image: nginx:stable-perl
    container_name: modu-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/html:/usr/share/nginx/html
      - ./frontend/logs:/var/log/nginx
    networks:
      - modu-network

networks:
  modu-network:
    driver: bridge

volumes:
  mongodb_data: