Databases:
  # tell pyannote.database where to find AMI wav files.
  # {uri} is a placeholder for the session name (eg. ES2004c).
  # you might need to update this line to fit your own setup.
  AMI: amicorpus/{uri}/audio/{uri}.Mix-Headset.wav
  AMI-SDM: amicorpus/{uri}/audio/{uri}.Array1-01.wav
  ALI: Train_Ali_far/audio_dir/{uri}.wav

Protocols:

  AMI-SDM:
    SpeakerDiarization:
      only_words:
        train:
            uri: ../lists/train.meetings.txt
            annotation: ../only_words/rttms/train/{uri}.rttm
            annotated: ../uems/train/{uri}.uem
        development:
            uri: ../lists/dev.meetings.txt
            annotation: ../only_words/rttms/dev/{uri}.rttm
            annotated: ../uems/dev/{uri}.uem
        test:
            uri: ../lists/test.meetings.txt
            annotation: ../only_words/rttms/test/{uri}.rttm
            annotated: ../uems/test/{uri}.uem
      mini:
        train:
          uri: ../lists/train.mini.txt
          annotation: ../only_words/rttms/train/{uri}.rttm
          annotated: ../uems/train/{uri}.uem
        development:
          uri: ../lists/dev.mini.txt
          annotation: ../only_words/rttms/dev/{uri}.rttm
          annotated: ../uems/dev/{uri}.uem
        test:
          uri: ../lists/test.mini.txt
          annotation: ../only_words/rttms/test/{uri}.rttm
          annotated: ../uems/test/{uri}.uem

  AMI:
    SpeakerDiarization:
      only_words:
        train:
            uri: ../lists/train.meetings.txt
            annotation: ../only_words/rttms/train/{uri}.rttm
            annotated: ../uems/train/{uri}.uem
        development:
            uri: ../lists/dev.meetings.txt
            annotation: ../only_words/rttms/dev/{uri}.rttm
            annotated: ../uems/dev/{uri}.uem
        test:
            uri: ../lists/test.meetings.txt
            annotation: ../only_words/rttms/test/{uri}.rttm
            annotated: ../uems/test/{uri}.uem

      mini:
        train:
          uri: ../lists/train.mini.txt
          annotation: ../only_words/rttms/train/{uri}.rttm
          annotated: ../uems/train/{uri}.uem
        development:
          uri: ../lists/dev.mini.txt
          annotation: ../only_words/rttms/dev/{uri}.rttm
          annotated: ../uems/dev/{uri}.uem
        test:
          uri: ../lists/test.mini.txt
          annotation: ../only_words/rttms/test/{uri}.rttm
          annotated: ../uems/test/{uri}.uem
 
      word_and_vocalsounds:
        train:
            uri: ../lists/train.meetings.txt
            annotation: ../word_and_vocalsounds/rttms/train/{uri}.rttm
            annotated: ../uems/train/{uri}.uem
        development:
            uri: ../lists/dev.meetings.txt
            annotation: ../word_and_vocalsounds/rttms/dev/{uri}.rttm
            annotated: ../uems/dev/{uri}.uem
        test:
            uri: ../lists/test.meetings.txt
            annotation: ../word_and_vocalsounds/rttms/test/{uri}.rttm
            annotated: ../uems/test/{uri}.uem
  
  ALI:
    SpeakerDiarization:
      koko:
        train:
          uri: Train_Ali_far/train_list.txt
          annotation: Train_Ali_far/rttm/train/{uri}.rttm
          annotated: Train_Ali_far/uem/train/{uri}.uem
        development:
          uri: Train_Ali_far/dev_list.txt
          annotation: Train_Ali_far/rttm/dev/{uri}.rttm
          annotated: Train_Ali_far/uem/dev/{uri}.uem
        test:
          uri: Train_Ali_far/test_list.txt
          annotation: Train_Ali_far/rttm/test/{uri}.rttm
          annotated: Train_Ali_far/uem/test/{uri}.uem


      